#!/usr/bin/env bash
set -eo pipefail

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

if [ "${BUILDKITE_PLUGIN_TAG_RELEASE_MARK_COMPLETED}" == "true" ]
then
  $basedir/lib/tag-release.sh "current" "pending" "previous" "${BUILDKITE_PLUGIN_TAG_RELEASE_TAG_IDENTIFIER}"
fi
