#!/usr/bin/env bash
set -eo pipefail

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

echo "${BUILDKITE_PLUGIN_BUILDKITE_TAG_RELEASE_RELEASE_COMPLETE}"

if [ "${BUILDKITE_PLUGIN_BUILDKITE_TAG_RELEASE_RELEASE_COMPLETE}" != "true" ]
then
    . $basedir/lib/tag-release.sh "pending"
fi
